### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by errantSquam** [errantSquam/twewy-message-generator#1]
**Basic Functionality**
- [x] Optimize images for web view (Update: Seems to be running fine now...?)
- [x] Implement the rest of the characters
- [x] More Dialogue Bubble options
- [ ] Thin dialogue bubbles
- [ ] Black overlay to focus in on a character

**Would be nice but takes effort**
- [ ] Character spacing tweaks
- [ ] Height overrides for specific portraits
- [ ] Properly naming the backgrounds and expressions
- [ ] Mobile support

**Might be fun?**
- [ ] Custom image uploads
- [ ] Manual Character spacing tweaks (for user)
